HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:3000
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 379
ETag: W/"17b-B6fOASMe+O992pnLgCaoJKn9BoM"
Date: Thu, 05 Feb 2026 00:54:30 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"user":{"id":"6983d9faf4675a93f7cc800b","fullName":"Admin Sistema QA","email":"administrador@example.com","role":"admin","avatarUrl":"https://example.com/qa-admin.jpg"},"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTgzZDlmYWY0Njc1YTkzZjdjYzgwMGIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzAyNTI4NzAsImV4cCI6MTc3MDg1NzY3MH0.QpLzjPoIzw56PSK2r789WAR9zrl_xZpCbBWpjTMxWtQ"}