HTTP/1.1 404 Not Found
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:3000
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 52
ETag: W/"34-RZx3/XeStm7/sUs57tZGZbDVzvo"
Date: Thu, 05 Feb 2026 00:55:11 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"error":{"code":"NOT_FOUND","message":"Not found"}}