HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:3000
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 170
ETag: W/"aa-t4tivjqjUiY4z91d2MOvJVQD/NQ"
Date: Thu, 05 Feb 2026 00:53:17 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"user":{"id":"6983d9faf4675a93f7cc800b","fullName":"Admin Sistema QA","email":"administrador@example.com","role":"admin","avatarUrl":"https://example.com/qa-admin.jpg"}}